{
  pkgs,
  ...
}:

{
  home.packages = with pkgs; [
    agenix
    ansible
    atac
    audacity
    bear
    blender
    bviplus
    cowsay
    cyberchef
    desmume
    diebahn
    dnsutils
    dragon-drop
    eza
    file
    file-roller
    font-manager
    ghidra
    ghostscript
    gimp
    gnome-characters
    gnome-clocks
    gnumake
    hieroglyphic
    imagemagick
    inkscape
    ipinfo
    jellyfin-desktop
    jetbrains.idea
    karere
    ldapvi
    libnotify
    libqalculate
    libreoffice
    # llvmPackages_latest.clang-manpages TODO: add back when not broken anymore
    # llvmPackages_latest.llvm-manpages TODO: "
    # logseq TODO: add back after v2 release
    lolcat
    nix-diff
    nix-inspect
    nix-output-monitor
    nix-tree
    nixln-edit
    nmap
    ocamlPackages.utop
    openldap
    openssl
    papers
    pdfarranger
    pdftk
    pgcli
    planify
    poppler-utils
    postman
    prismlauncher
    proton-vpn
    protonmail-desktop
    prusa-slicer
    pv
    qemu
    quickemu
    showtime
    signal-desktop
    speedread
    spotify
    spotify-tray
    sshfs
    telegram-desktop
    texliveMedium
    traceroute
    unar
    usbutils
    wev
    wireshark
    xournalpp
    yubioath-flutter
  ];
}
